//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamQuestion
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int VideoID { get; set; }
        public string Content { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> Score { get; set; }
    }
}
